(function(){'use strict';
const ar=document.documentElement.lang==='ar';
const main=document.querySelector('main[data-account-surface]');if(!main||!/account\/(billing|subscription)\/$/.test(main.getAttribute('data-account-surface')||''))return;
const address='ltc1qzq97jf6dk9v3tuetc0zlwtz7wuasrc5s4zt6qu';
const section=document.createElement('section');section.className='market-section';section.id='live-billing';
section.innerHTML='<div class="market-section-head"><span class="eyebrow">'+(ar?'الدفع':'Payment')+'</span><h2>'+(ar?'الدفع بواسطة لايتكوين':'Pay with Litecoin')+'</h2></div><div class="market-panel billing-live-panel"><p>'+(ar?'طريقة الدفع الحالية الوحيدة هي Litecoin (LTC). أرسل الدفعة إلى العنوان التالي واحتفظ بمعرّف المعاملة (TXID).':'The only payment method currently accepted is Litecoin (LTC). Send payment to the address below and keep the transaction ID (TXID).')+'</p><div class="ltc-address" dir="ltr"><code>'+address+'</code></div><div class="billing-live-actions"><button type="button" data-copy-ltc>'+(ar?'نسخ عنوان LTC':'Copy LTC address')+'</button><a class="billing-ltc-link" href="litecoin:'+address+'">'+(ar?'فتح محفظة لايتكوين':'Open Litecoin wallet')+'</a></div><p class="market-copy" data-ltc-status>'+(ar?'لا ترسل أي عملة أو شبكة أخرى إلى هذا العنوان.':'Do not send any other asset or network to this address.')+'</p></div>';
const hero=main.querySelector('.market-hero');if(hero)hero.insertAdjacentElement('afterend',section);else main.prepend(section);
const btn=section.querySelector('[data-copy-ltc]'),status=section.querySelector('[data-ltc-status]');btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);status.textContent=ar?'تم نسخ عنوان لايتكوين.':'Litecoin address copied.';}catch{status.textContent=address;}});
})();
