(function () {
  const translations = {
    ar: {
      meta: { locale: "ar_AR", homeTitle: "TradeAlpha AI | نظام تداول ذهبي مع أداء موثق", homeDescription: "TradeAlpha AI هو نظام تداول ذهبي احترافي مع مراجعة أداء موثقة عبر Myfxbook، تسعير واضح، ووصول مباشر عبر تيليجرام.", homeUrl: "https://www.tradealphaai.com/", homeOgType: "website", performanceTitle: "TradeAlpha AI | صفحة أداء موثقة لتداول الذهب", performanceDescription: "صفحة أداء مخصصة لـ TradeAlpha AI تعرض ملخص الأداء المباشر، حالة آخر تحديث، ورابط التحقق الخارجي عبر Myfxbook.", performanceUrl: "https://www.tradealphaai.com/performance/tradealpha-ai.html", performanceOgType: "website", image: "https://www.tradealphaai.com/Image/og-image.svg", imageAlt: "معاينة TradeAlpha AI", twitterCard: "summary_large_image" },
      pill: "العربية", "brand.tagline": "Gold Trading System", "nav.why": "لماذا TradeAlpha", "nav.about": "من نحن", "nav.product": "المنتج", "nav.proof": "الشفافية",
      "hero.tickerName": "TradeAlpha AI", "hero.tickerMarket": "سوق الذهب", "hero.tickerAccess": "وصول يدوي عبر تيليجرام", "hero.title": "TradeAlpha AI لتداول الذهب بثقة ووضوح", "hero.lead": "نظام تداول ذهبي بهوية احترافية، نهج منضبط، ووصول مباشر للمتداول الذي يبحث عن تجربة أكثر جدية ونظافة.", "hero.cta": "استعرض TradeAlpha AI", "hero.support": "وصول مباشر عبر تيليجرام مع تجربة اشتراك شخصية وسريعة.", "hero.proof.market.label": "السوق", "hero.proof.market.value": "الذهب", "hero.proof.risk.label": "المخاطر", "hero.proof.risk.value": "متوسطة",
      "overview.kicker": "نظرة عامة", "overview.status": "قيد التشغيل", "overview.lead": "عرض مركز يوضح السوق المستهدف، ملف المخاطرة، طريقة الوصول، ومصدر التحقق الخارجي في واجهة واحدة واضحة.", "overview.row1.key": "النظام", "overview.row1.value": "TradeAlpha AI", "overview.row2.key": "السوق", "overview.row2.value": "الذهب", "overview.row3.key": "ملف المخاطر", "overview.row3.value": "متوسطة", "overview.row4.key": "الوصول", "overview.row4.value": "تسليم عبر تيليجرام", "overview.verify.label": "التحقق", "overview.verify.value": "Myfxbook",
      "why.eyebrow": "لماذا TradeAlpha", "why.title": "وضوح يليق بمنتج مالي جاد", "why.lead": "TradeAlpha AI يقدم عرضاً مركزاً ومهنياً، حيث تكون الرسالة واضحة: منطق منضبط، مخاطرة مفهومة، وشفافية تدعم القرار.", "why.card1.kicker": "الثقة", "why.card1.title": "تقديم مالي أكثر نضجاً", "why.card1.body": "رسالة مركزة تضع القيمة في الواجهة: تجربة احترافية، تقديم واضح، ومظهر يليق بمنتج تداول عالي الثقة.", "why.card2.kicker": "منطق النظام", "why.card2.title": "تصنيف أوضح للمنهجية", "why.card2.body": "النظام مبني حول تداول الذهب بمنهج واضح وسهل القراءة، ما يمنح المتداول فهماً أسرع لما يقدمه المنتج فعلاً.", "why.card3.kicker": "ضبط المخاطر", "why.card3.title": "المخاطر جزء من العرض", "why.card3.body": "السوق المستهدف وملف المخاطرة معروضان بوضوح، حتى يبقى القرار مبنياً على فهم عملي لا على وعود عامة.", "why.card4.kicker": "الشفافية", "why.card4.title": "أداء يمكن مراجعته", "why.card4.body": "إثبات الأداء متاح عبر مصدر خارجي موثوق، بما يحافظ على نظافة العرض ووضوحه.",
      "about.eyebrow": "من نحن", "about.title": "عن TradeAlpha AI", "about.lead": "TradeAlpha AI هو نظام تداول ذهبي مركز، مبني حول منطق يتبع الاتجاه مع تركيز واضح على الانضباط، ضبط المخاطر، والشفافية في متابعة الأداء.", "founder.kicker": "المؤسس", "founder.title": "Wajd", "founder.p1": "تم تطوير TradeAlpha AI بواسطة Wajd متداول يركز على سوق الذهب منذ عام 2017.", "founder.p2": "على مدار السنوات كان التركيز دائما على بناء نهج تداول منضبط يعتمد على قراءة الاتجاه وإدارة المخاطر بدلا من مطاردة الأرباح السريعة.", "founder.p3": "TradeAlpha AI هو نتيجة هذا النهج:\nنظام واضح بدون تعقيد وبدون وعود مبالغ فيها.", "founder.p4": "جميع النتائج يتم تتبعها بشكل علني عبر Myfxbook بحيث يمكن لأي شخص مراجعة الأداء الفعلي في أي وقت.", "founder.p5": "إذا كنت تبحث عن تجربة تداول أكثر هدوءا وانضباطا يمكنك البدء مباشرة عبر البوت أو متابعة الأداء قبل اتخاذ القرار.", "about.card1.kicker": "التركيز", "about.card1.title": "تركيز واضح على الذهب", "about.card1.body": "النظام موجه لسوق الذهب مع تقديم مختصر وواضح يساعد المتداول على فهم طبيعة المنتج بسرعة.", "about.card2.kicker": "المنهج", "about.card2.title": "منهج يتبع الاتجاه بانضباط", "about.card2.body": "المنطق التشغيلي يركز على الوضوح والانضباط، مع تقديم يعكس وعياً بالمخاطر أكثر من الاعتماد على الوعود التسويقية.", "about.card3.kicker": "الشفافية", "about.card3.title": "متابعة أداء شفافة", "about.card3.body": "الأداء يراجع من خلال رابط تحقق خارجي واضح، بما يمنح المتداول نقطة مرجعية مباشرة قبل الاشتراك.",
      "product.eyebrow": "المنتج", "product.title": "TradeAlpha AI", "product.lead": "نظام تداول ذهبي مصمم للمتداول الذي يريد عرضاً واضحاً، تسعيراً مباشراً، ومسار وصول بسيط من دون تعقيد.", "product.badge": "متاح الآن", "product.type": "TradeAlpha AI", "product.card.title": "TradeAlpha AI", "product.card.description": "نظام تداول موجه للذهب بملف مخاطرة متوسط، مصمم ليقدم تجربة دخول واضحة ومباشرة للمتداول الجاد.", "product.meta1.label": "الاسم", "product.meta1.value": "TradeAlpha AI", "product.meta2.label": "السوق", "product.meta2.value": "الذهب", "product.meta3.label": "المخاطر", "product.meta3.value": "متوسطة", "product.meta4.label": "شهري", "product.meta4.value": "$40", "product.meta5.label": "سنوي", "product.meta5.value": "$400", "product.cta": "اشترك عبر تيليجرام", "product.note": "يتم إرسال تفاصيل الوصول عبر تيليجرام بعد تأكيد الاشتراك.",
      "proof.eyebrow": "الأداء والشفافية", "proof.title": "شفافية يمكن الرجوع إليها مباشرة", "proof.lead": "الأداء متاح للمراجعة عبر صفحة Myfxbook العامة، بما يمنح الزائر وسيلة تحقق خارجية واضحة ومباشرة.", "proof.metric1.label": "إجمالي العائد", "proof.metric2.label": "التراجع", "proof.metric3.label": "الصفقات", "proof.updated.label": "آخر تحديث", "proof.note": "راجع صفحة الأداء أو Myfxbook للاطلاع على الأداء من المصدر المرجعي مباشرة.", "proof.cta": "عرض أداء TradeAlpha AI", "proof.side.kicker": "التحقق", "proof.side.title": "ثقة مبنية على الوضوح", "proof.side.body": "صفحة أداء مخصصة تمنح المتداول نقطة مراجعة واضحة قبل الانتقال إلى مصدر التحقق الخارجي.",
      "final.eyebrow": "الخطوة التالية", "final.title": "ابدأ مع TradeAlpha AI عبر تيليجرام", "final.lead": "ابدأ طلب الوصول الآن، وسنرسل لك تفاصيل الاشتراك والوصول عبر تيليجرام بخطوات واضحة وسريعة.", "final.ctaPrimary": "ابدأ عبر بوت تيليجرام", "final.ctaSecondary": "انضم إلى القناة الرسمية", "final.support": "القناة الرسمية مخصصة للتحديثات العامة، بينما يتم بدء الاشتراك والوصول عبر البوت.", "risk.eyebrow": "تحذير المخاطر", "risk.copy": "تحذير المخاطر:\nالتداول في الأسواق المالية ينطوي على مخاطر عالية وقد يؤدي إلى خسارة رأس المال بالكامل.\nالأداء السابق لا يضمن النتائج المستقبلية.\nلا تستثمر أكثر مما تستطيع تحمل خسارته.", "footer.tagline": "وصول احترافي لتداول الذهب عبر تيليجرام.", "footer.socialLabel": "القنوات الرسمية",
      "perf.brand.tagline": "Performance Page", "perf.nav.product": "المنتج", "perf.nav.verify": "التحقق", "perf.nav.telegram": "تيليجرام", "perf.hero.tickerName": "TradeAlpha AI", "perf.hero.tickerMarket": "الذهب", "perf.hero.tickerRisk": "مخاطر متوسطة", "perf.hero.title": "صفحة أداء TradeAlpha AI", "perf.hero.lead": "متابعة أداء مخصصة لمنتج TradeAlpha AI، مع ملخص مباشر، حالة آخر تحديث، ورابط تحقق خارجي عبر Myfxbook.", "perf.hero.ctaPrimary": "اشترك عبر تيليجرام", "perf.hero.ctaSecondary": "العودة إلى الموقع الرئيسي", "perf.profile.kicker": "ملف المنتج", "perf.profile.status": "تتبع مباشر", "perf.profile.row1.key": "المنتج", "perf.profile.row1.value": "TradeAlpha AI", "perf.profile.row2.key": "السوق", "perf.profile.row2.value": "الذهب", "perf.profile.row3.key": "ملف المخاطر", "perf.profile.row3.value": "متوسطة", "perf.profile.row4.key": "التحقق", "perf.profile.row4.value": "Myfxbook", "perf.section.eyebrow": "الأداء المباشر", "perf.section.title": "ملخص الأداء المباشر", "perf.section.lead": "هذه الصفحة مخصصة لـ TradeAlpha AI فقط، وتعرض مؤشرات الأداء الحية كما تصل من المصدر المتصل، مع زر تحقق خارجي واضح.", "perf.metric1.label": "إجمالي العائد", "perf.metric2.label": "التراجع", "perf.metric3.label": "الصفقات", "perf.updated.label": "آخر تحديث", "perf.note": "يمكن مراجعة الأداء من المصدر المرجعي مباشرة عبر زر التحقق الخارجي أدناه.", "perf.cta": "فتح Myfxbook الموثق", "perf.side.kicker": "سياق الأداء", "perf.side.title": "مخصصة لـ TradeAlpha AI", "perf.side.body": "تعرض هذه الصفحة أداء TradeAlpha AI ضمن مساحة مستقلة وواضحة، بما يسمح بإضافة صفحات أداء منفصلة لمنتجات مستقبلية ضمن نفس الهيكل."
    },
    en: {
      meta: { locale: "en_US", homeTitle: "TradeAlpha AI | Gold Trading System with Verified Performance", homeDescription: "TradeAlpha AI is a premium gold trading system with medium risk positioning, verified Myfxbook performance review, and direct Telegram delivery.", homeUrl: "https://www.tradealphaai.com/", homeOgType: "website", performanceTitle: "TradeAlpha AI Performance | Verified Gold Trading Results", performanceDescription: "Review the dedicated TradeAlpha AI performance page with live summary fields, latest update state, and direct Myfxbook verification.", performanceUrl: "https://www.tradealphaai.com/performance/tradealpha-ai.html", performanceOgType: "website", image: "https://www.tradealphaai.com/Image/og-image.svg", imageAlt: "TradeAlpha AI preview", twitterCard: "summary_large_image" },
      pill: "English", "brand.tagline": "Gold Trading System", "nav.why": "Why TradeAlpha", "nav.about": "About", "nav.product": "Product", "nav.proof": "Transparency",
      "hero.tickerName": "TradeAlpha AI", "hero.tickerMarket": "Gold Market", "hero.tickerAccess": "Manual Telegram Access", "hero.title": "TradeAlpha AI for gold trading with clarity and control", "hero.lead": "A focused gold trading system with a premium identity, disciplined logic, and direct access for traders who want a more serious operating experience.", "hero.cta": "Explore TradeAlpha AI", "hero.support": "Direct Telegram access with a clear and personal subscription flow.", "hero.proof.market.label": "Market", "hero.proof.market.value": "Gold", "hero.proof.risk.label": "Risk", "hero.proof.risk.value": "Medium",
      "overview.kicker": "System Overview", "overview.status": "Operational", "overview.lead": "A focused overview of the target market, risk profile, access method, and external verification source in one clear interface.", "overview.row1.key": "System", "overview.row1.value": "TradeAlpha AI", "overview.row2.key": "Market", "overview.row2.value": "Gold", "overview.row3.key": "Risk Profile", "overview.row3.value": "Medium", "overview.row4.key": "Access", "overview.row4.value": "Telegram Delivery", "overview.verify.label": "Verification", "overview.verify.value": "Myfxbook",
      "why.eyebrow": "Why TradeAlpha", "why.title": "Clarity suited to a serious trading product", "why.lead": "TradeAlpha AI presents a controlled and professional offer built around disciplined logic, understood risk, and transparency that supports better decisions.", "why.card1.kicker": "Trust", "why.card1.title": "A more mature financial presentation", "why.card1.body": "The message stays focused on what matters: professional delivery, clear positioning, and a presentation aligned with a serious trading product.", "why.card2.kicker": "System Logic", "why.card2.title": "Clearer product logic", "why.card2.body": "The system is positioned around gold trading with a readable structure that helps visitors understand what the product actually does.", "why.card3.kicker": "Risk Control", "why.card3.title": "Risk is part of the presentation", "why.card3.body": "The target market and risk profile are shown plainly so the decision is based on operating context, not broad promises.", "why.card4.kicker": "Transparency", "why.card4.title": "Performance can be reviewed", "why.card4.body": "Performance is referenced through a trusted external source, keeping the presentation clean and verifiable.",
      "about.eyebrow": "About", "about.title": "Who We Are", "about.lead": "TradeAlpha AI is a focused gold trading system built around trend-following logic, disciplined execution, risk control, and transparent performance review.", "founder.kicker": "Founder", "founder.title": "Wajd", "founder.p1": "TradeAlpha AI was developed by Wajd, a trader focused on the gold market since 2017.", "founder.p2": "Over the years, the focus has been on building a disciplined trading approach based on trend reading and risk management, rather than chasing quick profits.", "founder.p3": "TradeAlpha AI reflects that philosophy:\na clear system, without unnecessary complexity or exaggerated claims.", "founder.p4": "All performance is tracked publicly via Myfxbook, allowing anyone to verify results transparently at any time.", "founder.p5": "If you're looking for a more structured and controlled trading experience, you can start directly via the bot, or monitor the performance before making a decision.", "about.card1.kicker": "Focus", "about.card1.title": "A clear focus on gold", "about.card1.body": "The system is built for the gold market and presented in a direct format that makes the product easy to understand.", "about.card2.kicker": "Logic", "about.card2.title": "Trend-following logic with discipline", "about.card2.body": "The operating approach favors clarity and control, with a tone grounded in risk awareness rather than exaggerated promises.", "about.card3.kicker": "Transparency", "about.card3.title": "Transparent performance review", "about.card3.body": "Performance is reviewed through a clear external verification path, giving traders a direct reference point before subscribing.",
      "product.eyebrow": "Product", "product.title": "TradeAlpha AI", "product.lead": "A gold trading system for traders who want a clear offer, direct pricing, and a simple access path without unnecessary complexity.", "product.badge": "Available Now", "product.type": "TradeAlpha AI", "product.card.title": "TradeAlpha AI", "product.card.description": "A gold-focused trading system with a medium risk profile, built to offer a clear and direct entry point for serious traders.", "product.meta1.label": "Name", "product.meta1.value": "TradeAlpha AI", "product.meta2.label": "Market", "product.meta2.value": "Gold", "product.meta3.label": "Risk", "product.meta3.value": "Medium", "product.meta4.label": "Monthly", "product.meta4.value": "$40", "product.meta5.label": "Yearly", "product.meta5.value": "$400", "product.cta": "Subscribe via Telegram", "product.note": "Access details are delivered manually on Telegram after payment confirmation.",
      "proof.eyebrow": "Performance / Trust", "proof.title": "Transparency you can review directly", "proof.lead": "Performance is available through the public Myfxbook page, giving visitors a clear and external verification path.", "proof.metric1.label": "Total Gain", "proof.metric2.label": "Drawdown", "proof.metric3.label": "Trades", "proof.updated.label": "Last Updated", "proof.note": "Review the dedicated performance page or Myfxbook for source-level performance verification.", "proof.cta": "View TradeAlpha AI Performance", "proof.side.kicker": "Verification", "proof.side.title": "Trust built on clarity", "proof.side.body": "A dedicated performance page gives traders a clean review point before opening the external verification source.",
      "final.eyebrow": "Next Step", "final.title": "Start with TradeAlpha AI on Telegram", "final.lead": "Request access now and receive subscription and activation details through a clear Telegram-based flow.", "final.ctaPrimary": "Start via Telegram Bot", "final.ctaSecondary": "Join Official Channel", "final.support": "The official channel is for public updates, while subscription and access start through the bot.", "risk.eyebrow": "Risk Disclaimer", "risk.copy": "Risk Disclaimer:\nTrading involves significant risk and may result in the loss of your capital.\nPast performance does not guarantee future results.\nOnly trade with money you can afford to lose.", "footer.tagline": "Professional gold trading access through Telegram.", "footer.socialLabel": "Official Channels",
      "perf.brand.tagline": "Performance Page", "perf.nav.product": "Product", "perf.nav.verify": "Verification", "perf.nav.telegram": "Telegram", "perf.hero.tickerName": "TradeAlpha AI", "perf.hero.tickerMarket": "Gold", "perf.hero.tickerRisk": "Medium Risk", "perf.hero.title": "TradeAlpha AI Performance Page", "perf.hero.lead": "A dedicated performance page for TradeAlpha AI with live summary fields, last-updated status, and external Myfxbook verification.", "perf.hero.ctaPrimary": "Subscribe via Telegram", "perf.hero.ctaSecondary": "Back to Main Site", "perf.profile.kicker": "Product Profile", "perf.profile.status": "Live Tracking", "perf.profile.row1.key": "Product", "perf.profile.row1.value": "TradeAlpha AI", "perf.profile.row2.key": "Market", "perf.profile.row2.value": "Gold", "perf.profile.row3.key": "Risk Profile", "perf.profile.row3.value": "Medium", "perf.profile.row4.key": "Verification", "perf.profile.row4.value": "Myfxbook", "perf.section.eyebrow": "Live Performance", "perf.section.title": "Live performance summary", "perf.section.lead": "This page is dedicated to TradeAlpha AI and presents live performance fields as they arrive from the connected source, with a clear external verification path.", "perf.metric1.label": "Total Gain", "perf.metric2.label": "Drawdown", "perf.metric3.label": "Trades", "perf.updated.label": "Last Updated", "perf.note": "Review the reference source directly through the external verification button below.", "perf.cta": "Open Verified Myfxbook", "perf.side.kicker": "Performance Context", "perf.side.title": "Dedicated to TradeAlpha AI", "perf.side.body": "This page presents TradeAlpha AI performance in a separate, structured view, making it straightforward to add dedicated performance pages for future products later."
    },
    de: {
      meta: { locale: "de_DE", homeTitle: "TradeAlpha AI | Gold-Trading-System mit verifizierter Performance", homeDescription: "TradeAlpha AI ist ein hochwertiges Gold-Trading-System mit mittlerem Risikoprofil, verifizierter Myfxbook-Performance und direkter Telegram-Auslieferung.", homeUrl: "https://www.tradealphaai.com/", homeOgType: "website", performanceTitle: "TradeAlpha AI Performance | Verifizierte Gold-Trading-Ergebnisse", performanceDescription: "Prüfe die dedizierte TradeAlpha AI Performance-Seite mit Live-Zusammenfassung, Aktualisierungsstatus und direkter Myfxbook-Verifikation.", performanceUrl: "https://www.tradealphaai.com/performance/tradealpha-ai.html", performanceOgType: "website", image: "https://www.tradealphaai.com/Image/og-image.svg", imageAlt: "TradeAlpha AI Vorschau", twitterCard: "summary_large_image" },
      pill: "Deutsch", "brand.tagline": "Gold Trading System", "nav.why": "Warum TradeAlpha", "nav.about": "Über uns", "nav.product": "Produkt", "nav.proof": "Transparenz",
      "hero.tickerName": "TradeAlpha AI", "hero.tickerMarket": "Goldmarkt", "hero.tickerAccess": "Manueller Telegram-Zugang", "hero.title": "TradeAlpha AI für Gold-Trading mit Klarheit und Kontrolle", "hero.lead": "Ein fokussiertes Gold-Trading-System mit hochwertiger Identität, disziplinierter Logik und direktem Zugang für Trader, die eine ernsthaftere operative Erfahrung suchen.", "hero.cta": "TradeAlpha AI ansehen", "hero.support": "Direkter Telegram-Zugang mit klarem und persönlichem Subscription-Ablauf.", "hero.proof.market.label": "Markt", "hero.proof.market.value": "Gold", "hero.proof.risk.label": "Risiko", "hero.proof.risk.value": "Mittel",
      "overview.kicker": "Systemüberblick", "overview.status": "Aktiv", "overview.lead": "Ein fokussierter Überblick über Zielmarkt, Risikoprofil, Zugangsweg und externe Verifikationsquelle in einer klaren Oberfläche.", "overview.row1.key": "System", "overview.row1.value": "TradeAlpha AI", "overview.row2.key": "Markt", "overview.row2.value": "Gold", "overview.row3.key": "Risikoprofil", "overview.row3.value": "Mittel", "overview.row4.key": "Zugang", "overview.row4.value": "Telegram-Auslieferung", "overview.verify.label": "Verifikation", "overview.verify.value": "Myfxbook",
      "why.eyebrow": "Warum TradeAlpha", "why.title": "Klarheit für ein ernsthaftes Trading-Produkt", "why.lead": "TradeAlpha AI präsentiert ein kontrolliertes und professionelles Angebot, das auf disziplinierter Logik, nachvollziehbarem Risiko und Transparenz basiert.", "why.card1.kicker": "Vertrauen", "why.card1.title": "Ein reiferer finanzieller Auftritt", "why.card1.body": "Die Botschaft bleibt auf das Wesentliche fokussiert: professionelle Präsentation, klare Positionierung und ein Auftritt passend zu einem ernsthaften Trading-Produkt.", "why.card2.kicker": "Systemlogik", "why.card2.title": "Klarere Produktlogik", "why.card2.body": "Das System ist um Gold-Trading aufgebaut und so strukturiert, dass Besucher schnell verstehen, was das Produkt tatsächlich liefert.", "why.card3.kicker": "Risikokontrolle", "why.card3.title": "Risiko ist Teil der Darstellung", "why.card3.body": "Zielmarkt und Risikoprofil werden offen dargestellt, damit die Entscheidung auf operativem Kontext statt auf allgemeinen Versprechen basiert.", "why.card4.kicker": "Transparenz", "why.card4.title": "Performance ist überprüfbar", "why.card4.body": "Die Performance wird über eine vertrauenswürdige externe Quelle referenziert und bleibt dadurch sauber und nachvollziehbar.",
      "about.eyebrow": "Über uns", "about.title": "Wer wir sind", "about.lead": "TradeAlpha AI ist ein fokussiertes Gold-Trading-System, aufgebaut auf trendfolgender Logik, disziplinierter Ausführung, Risikokontrolle und transparenter Performance-Prüfung.", "founder.kicker": "Gründer", "founder.title": "Wajd", "founder.p1": "TradeAlpha AI wurde von Wajd entwickelt, einem Trader mit Fokus auf den Goldmarkt seit 2017.", "founder.p2": "Im Laufe der Jahre lag der Schwerpunkt darauf, einen disziplinierten Handelsansatz aufzubauen, der auf Trendanalyse und Risikomanagement basiert, anstatt schnellen Gewinnen nachzujagen.", "founder.p3": "TradeAlpha AI spiegelt genau diese Philosophie wider:\nein klares System, ohne unnötige Komplexität und ohne übertriebene Versprechen.", "founder.p4": "Alle Ergebnisse werden öffentlich über Myfxbook verfolgt, sodass jeder die tatsächliche Performance jederzeit transparent überprüfen kann.", "founder.p5": "Wenn du nach einem strukturierteren und kontrollierteren Trading-Ansatz suchst, kannst du direkt über den Bot starten oder zuerst die Performance beobachten, bevor du eine Entscheidung triffst.", "about.card1.kicker": "Fokus", "about.card1.title": "Klarer Fokus auf Gold", "about.card1.body": "Das System ist auf den Goldmarkt ausgerichtet und in einem direkten Format dargestellt, das das Produkt leicht verständlich macht.", "about.card2.kicker": "Logik", "about.card2.title": "Trendfolgende Logik mit Disziplin", "about.card2.body": "Der operative Ansatz setzt auf Klarheit und Kontrolle und bleibt im Ton risikobewusst statt überzogen werblich.", "about.card3.kicker": "Transparenz", "about.card3.title": "Transparente Performance-Prüfung", "about.card3.body": "Die Performance wird über einen klaren externen Verifikationsweg geprüft und gibt Tradern vor der Subscription einen direkten Referenzpunkt.",
      "product.eyebrow": "Produkt", "product.title": "TradeAlpha AI", "product.lead": "Ein Gold-Trading-System für Trader, die ein klares Angebot, direkte Preise und einen einfachen Zugangsweg ohne unnötige Komplexität wollen.", "product.badge": "Jetzt verfügbar", "product.type": "TradeAlpha AI", "product.card.title": "TradeAlpha AI", "product.card.description": "Ein Gold-Trading-System mit mittlerem Risikoprofil, entwickelt als klarer und direkter Einstiegspunkt für ernsthafte Trader.", "product.meta1.label": "Name", "product.meta1.value": "TradeAlpha AI", "product.meta2.label": "Markt", "product.meta2.value": "Gold", "product.meta3.label": "Risiko", "product.meta3.value": "Mittel", "product.meta4.label": "Monatlich", "product.meta4.value": "$40", "product.meta5.label": "Jährlich", "product.meta5.value": "$400", "product.cta": "Per Telegram abonnieren", "product.note": "Die Zugangsdaten werden nach Zahlungsbestätigung manuell über Telegram übermittelt.",
      "proof.eyebrow": "Performance / Vertrauen", "proof.title": "Transparenz, die direkt geprüft werden kann", "proof.lead": "Die Performance ist über die öffentliche Myfxbook-Seite verfügbar und bietet Besuchern einen klaren externen Verifikationsweg.", "proof.metric1.label": "Gesamtertrag", "proof.metric2.label": "Drawdown", "proof.metric3.label": "Trades", "proof.updated.label": "Zuletzt aktualisiert", "proof.note": "Prüfe die dedizierte Performance-Seite oder Myfxbook für die Verifikation auf Quellenebene.", "proof.cta": "TradeAlpha AI Performance ansehen", "proof.side.kicker": "Verifikation", "proof.side.title": "Vertrauen durch Klarheit", "proof.side.body": "Eine dedizierte Performance-Seite gibt Tradern einen sauberen Prüfpunkt, bevor sie die externe Verifikationsquelle öffnen.",
      "final.eyebrow": "Nächster Schritt", "final.title": "Mit TradeAlpha AI auf Telegram starten", "final.lead": "Zugang jetzt anfragen und Subscription- sowie Aktivierungsdetails über einen klaren Telegram-Ablauf erhalten.", "final.ctaPrimary": "Über Telegram-Bot starten", "final.ctaSecondary": "Offiziellem Kanal beitreten", "final.support": "Der offizielle Kanal dient öffentlichen Updates, während Subscription und Zugang über den Bot starten.", "risk.eyebrow": "Risikohinweis", "risk.copy": "Risikohinweis:\nTrading ist mit erheblichen Risiken verbunden und kann zum Verlust des eingesetzten Kapitals führen.\nDie bisherige Performance garantiert keine zukünftigen Ergebnisse.\nHandle nur mit Kapital, dessen Verlust du dir leisten kannst.", "footer.tagline": "Professioneller Gold-Trading-Zugang über Telegram.", "footer.socialLabel": "Offizielle Kanäle",
      "perf.brand.tagline": "Performance-Seite", "perf.nav.product": "Produkt", "perf.nav.verify": "Verifikation", "perf.nav.telegram": "Telegram", "perf.hero.tickerName": "TradeAlpha AI", "perf.hero.tickerMarket": "Gold", "perf.hero.tickerRisk": "Mittleres Risiko", "perf.hero.title": "TradeAlpha AI Performance-Seite", "perf.hero.lead": "Eine dedizierte Performance-Seite für TradeAlpha AI mit Live-Zusammenfassung, Aktualisierungsstatus und externer Myfxbook-Verifikation.", "perf.hero.ctaPrimary": "Per Telegram abonnieren", "perf.hero.ctaSecondary": "Zurück zur Hauptseite", "perf.profile.kicker": "Produktprofil", "perf.profile.status": "Live-Tracking", "perf.profile.row1.key": "Produkt", "perf.profile.row1.value": "TradeAlpha AI", "perf.profile.row2.key": "Markt", "perf.profile.row2.value": "Gold", "perf.profile.row3.key": "Risikoprofil", "perf.profile.row3.value": "Mittel", "perf.profile.row4.key": "Verifikation", "perf.profile.row4.value": "Myfxbook", "perf.section.eyebrow": "Live-Performance", "perf.section.title": "Live-Performance-Zusammenfassung", "perf.section.lead": "Diese Seite ist ausschließlich TradeAlpha AI gewidmet und zeigt Live-Performance-Felder aus der verbundenen Quelle sowie einen klaren externen Verifikationsweg.", "perf.metric1.label": "Gesamtertrag", "perf.metric2.label": "Drawdown", "perf.metric3.label": "Trades", "perf.updated.label": "Zuletzt aktualisiert", "perf.note": "Prüfe die Referenzquelle direkt über die externe Verifikations-Schaltfläche unten.", "perf.cta": "Verifiziertes Myfxbook öffnen", "perf.side.kicker": "Performance-Kontext", "perf.side.title": "Dediziert für TradeAlpha AI", "perf.side.body": "Diese Seite zeigt die Performance von TradeAlpha AI in einer separaten, strukturierten Ansicht und erleichtert spätere dedizierte Performance-Seiten für weitere Produkte."
    }
  };

  function getLanguage() {
    return localStorage.getItem("ta_lang") || document.documentElement.lang || "ar";
  }

  function getMeta(map) {
    const page = document.body.dataset.page;
    if (page === "performance") {
      return {
        title: map.meta.performanceTitle,
        description: map.meta.performanceDescription,
        url: map.meta.performanceUrl,
        type: map.meta.performanceOgType
      };
    }

    return {
      title: map.meta.homeTitle,
      description: map.meta.homeDescription,
      url: map.meta.homeUrl,
      type: map.meta.homeOgType
    };
  }

  function setMeta(selector, value, attribute) {
    const node = document.querySelector(selector);
    if (node && value) {
      node.setAttribute(attribute || "content", value);
    }
  }

  function applyLandingLanguage(lang) {
    const map = translations[lang] || translations.en;
    const meta = getMeta(map);

    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.title = meta.title;

    setMeta('meta[name="description"]', meta.description);
    setMeta('meta[property="og:locale"]', map.meta.locale);
    setMeta('meta[property="og:title"]', meta.title);
    setMeta('meta[property="og:description"]', meta.description);
    setMeta('meta[property="og:url"]', meta.url);
    setMeta('meta[property="og:type"]', meta.type);
    setMeta('meta[property="og:image"]', map.meta.image);
    setMeta('meta[property="og:image:alt"]', map.meta.imageAlt);
    setMeta('meta[name="twitter:card"]', map.meta.twitterCard);
    setMeta('meta[name="twitter:title"]', meta.title);
    setMeta('meta[name="twitter:description"]', meta.description);
    setMeta('meta[name="twitter:image"]', map.meta.image);
    setMeta('link[rel="canonical"]', meta.url, "href");

    document.querySelectorAll("[data-copy]").forEach(function (el) {
      const key = el.getAttribute("data-copy");
      if (Object.prototype.hasOwnProperty.call(map, key)) {
        el.textContent = map[key];
      }
    });

    const pill = document.querySelector("#langSwitch .pill");
    if (pill) {
      pill.textContent = map.pill;
    }

    document.body.style.textAlign = lang === "ar" ? "right" : "left";
    window.dispatchEvent(new CustomEvent("ta:languagechange", { detail: { lang: lang } }));
  }

  function syncLandingLanguage() {
    applyLandingLanguage(getLanguage());
  }

  document.addEventListener("DOMContentLoaded", function () {
    syncLandingLanguage();

    const year = document.getElementById("y3");
    if (year) {
      year.textContent = new Date().getFullYear();
    }

    document.querySelectorAll("[data-lang]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        const lang = btn.getAttribute("data-lang");
        localStorage.setItem("ta_lang", lang);
        applyLandingLanguage(lang);
      });
    });
  });

  window.addEventListener("storage", function (event) {
    if (event.key === "ta_lang") {
      syncLandingLanguage();
    }
  });

  window.applyLandingLanguage = applyLandingLanguage;
})();
