@echo off
setlocal EnableDelayedExpansion

set "PROJECT_DIR=C:\EA_AI\TradeAlphaAI Final"
set "PIPELINE_LOG=%TEMP%\tradealphaai-insight-pipeline.log"
set "DETECTED_SLUG="
set "PUBLIC_URL="
set "LOCAL_URL="

echo ========================================
echo TradeAlphaAI Publish Next Insight
echo ========================================
echo.

echo ========================================
echo 1. Change to project directory
echo ========================================
call cd /d "%PROJECT_DIR%"
if errorlevel 1 (
  echo.
  echo ERROR DETECTED
  pause
  goto :end
)
echo.

echo ========================================
echo 2. Discover insight topics
echo ========================================
call npm run insights:discover
if errorlevel 1 (
  echo.
  echo ERROR DETECTED
  pause
  goto :end
)
echo.

echo ========================================
echo 3. Run insights pipeline in review mode
echo ========================================
call npm run insights:pipeline > "%PIPELINE_LOG%" 2>&1
set "PIPELINE_EXIT=%ERRORLEVEL%"
type "%PIPELINE_LOG%"
if not "%PIPELINE_EXIT%"=="0" (
  echo.
  echo ERROR DETECTED
  pause
  goto :end
)

for /f "tokens=5" %%S in ('findstr /c:"Insight pipeline completed for" "%PIPELINE_LOG%"') do (
  set "DETECTED_SLUG=%%S"
)

if "%DETECTED_SLUG%"=="" (
  echo.
  echo No new article was generated by the review pipeline.
  echo Nothing will be published or pushed.
  pause
  goto :end
)

if not exist "%PROJECT_DIR%\insights\%DETECTED_SLUG%.html" (
  echo.
  echo ERROR DETECTED
  echo Expected article file was not found:
  echo "%PROJECT_DIR%\insights\%DETECTED_SLUG%.html"
  pause
  goto :end
)

echo.
echo Detected insight slug:
echo %DETECTED_SLUG%
echo.

echo ========================================
echo 4. Run quality gate
echo ========================================
call npm run insights:quality -- --slug=%DETECTED_SLUG%
if errorlevel 1 (
  echo.
  echo QUALITY CHECK FAILED
  echo Article was not published and GitHub push was skipped.
  pause
  goto :end
)
echo.

echo ========================================
echo 5. Publish safely
echo ========================================
call npm run insights:publish-safe -- --slug=%DETECTED_SLUG%
if errorlevel 1 (
  echo.
  echo PUBLISH-SAFE FAILED
  echo GitHub push was skipped.
  pause
  goto :end
)
echo.

echo ========================================
echo 6. Run production readiness checks
echo ========================================
call npm run check:production
if errorlevel 1 (
  echo.
  echo PRODUCTION CHECK FAILED
  echo GitHub push was skipped.
  pause
  goto :end
)
echo.

echo ========================================
echo 7. Git status
echo ========================================
call git status
if errorlevel 1 (
  echo.
  echo ERROR DETECTED
  pause
  goto :end
)
echo.

echo ========================================
echo 8. Stage changes
echo ========================================
call git add .
if errorlevel 1 (
  echo.
  echo ERROR DETECTED
  pause
  goto :end
)
echo.

echo ========================================
echo 9. Commit changes
echo ========================================
call git commit -m "Publish insight: %DETECTED_SLUG%"
if errorlevel 1 (
  echo.
  echo No commit was created. There may be nothing to commit.
  echo GitHub push will be skipped.
  pause
  goto :preview
)
echo.

echo ========================================
echo 10. Push to GitHub
echo ========================================
call git push origin main
if errorlevel 1 (
  echo.
  echo ERROR DETECTED
  pause
  goto :preview
)
echo.

:preview
set "PUBLIC_URL=https://tradealphaai.com/insights/%DETECTED_SLUG%.html"
set "LOCAL_URL=http://localhost:8098/insights/%DETECTED_SLUG%.html"

echo ========================================
echo Final Article URL
echo ========================================
echo %PUBLIC_URL%
echo.

echo ========================================
echo Open article preview
echo ========================================
call start "" "%PUBLIC_URL%"
if errorlevel 1 (
  echo Could not open public URL. Trying local preview URL.
  call start "" "%LOCAL_URL%"
)
echo.

:end
pause
endlocal
