const stockDefaults = {
  marketSession: "U.S. regular session",
  analystSentiment: "constructive",
  earningsSentiment: "neutral",
  allocation: null,
  holdings: []
};

const etfDefaults = {
  type: "etf",
  marketCap: "ETF",
  revenueGrowth: 0.08,
  profitMargin: 0.16,
  marketSession: "U.S. ETF session",
  analystSentiment: "fund flow neutral",
  earningsSentiment: "portfolio-level",
  expenseRatio: 0.09,
  issuer: "ETF Provider",
  category: "U.S. Equity ETF",
  holdings: [],
  allocation: {
    technology: 28,
    financials: 13,
    healthcare: 12,
    consumer: 10,
    industrials: 9,
    other: 28
  }
};

export const marketUniverse = {
  generatedAt: "2026-05-19",
  provider: "mock",
  marketStatus: "Mock data refreshed recently",
  assets: [
    withStockDefaults({
      symbol: "NVDA",
      type: "stock",
      name: "NVIDIA Corporation",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Semiconductors",
      price: 134.82,
      change: 2.41,
      changePercent: 1.82,
      marketCap: "3.31T",
      peRatio: 42.8,
      revenueGrowth: 0.78,
      profitMargin: 0.49,
      rsi: 66,
      macdTrend: "bullish",
      ma50: 121.4,
      ma200: 104.7,
      volumeTrend: "above average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.34,
      trendDirection: "uptrend",
      heat: "hot",
      analystSentiment: "AI infrastructure demand remains constructive",
      earningsSentiment: "positive",
      summary: "NVDA shows strong momentum and high growth characteristics, balanced by elevated valuation and volatility risk.",
      related: ["MSFT", "META", "AAPL", "QQQ"],
      contentAngles: ["AI infrastructure stocks", "semiconductor leaders", "accelerated computing demand"]
    }),
    withStockDefaults({
      symbol: "AAPL",
      type: "stock",
      name: "Apple Inc.",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Consumer Electronics",
      price: 189.36,
      change: -0.84,
      changePercent: -0.44,
      marketCap: "2.91T",
      peRatio: 29.4,
      revenueGrowth: 0.03,
      profitMargin: 0.26,
      rsi: 48,
      macdTrend: "neutral",
      ma50: 191.2,
      ma200: 184.8,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.21,
      trendDirection: "range",
      heat: "steady",
      analystSentiment: "product cycle expectations are balanced",
      earningsSentiment: "neutral",
      summary: "AAPL presents a mature large-cap profile with stable profitability, moderate momentum, and balanced risk conditions.",
      related: ["MSFT", "AMZN", "META", "SPY"],
      contentAngles: ["defensive technology", "cash flow quality", "consumer hardware cycle"]
    }),
    withStockDefaults({
      symbol: "TSLA",
      type: "stock",
      name: "Tesla, Inc.",
      exchange: "NASDAQ",
      sector: "Consumer Cyclical",
      industry: "Auto Manufacturers",
      price: 178.22,
      change: 4.12,
      changePercent: 2.37,
      marketCap: "568B",
      peRatio: 58.5,
      revenueGrowth: 0.11,
      profitMargin: 0.08,
      rsi: 71,
      macdTrend: "bullish",
      ma50: 164.9,
      ma200: 198.7,
      volumeTrend: "above average",
      sentiment: "mixed",
      risk: "high",
      volatility: 0.46,
      trendDirection: "rebound",
      heat: "volatile",
      analystSentiment: "delivery and margin expectations remain mixed",
      earningsSentiment: "mixed",
      summary: "TSLA has active momentum but remains a higher-risk screening candidate due to valuation sensitivity and volatility.",
      related: ["NVDA", "AMZN", "META", "QQQ"],
      contentAngles: ["high beta growth", "electric vehicle demand", "margin sensitivity"]
    }),
    withStockDefaults({
      symbol: "MSFT",
      type: "stock",
      name: "Microsoft Corporation",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Software Infrastructure",
      price: 429.75,
      change: 1.92,
      changePercent: 0.45,
      marketCap: "3.19T",
      peRatio: 35.2,
      revenueGrowth: 0.16,
      profitMargin: 0.36,
      rsi: 58,
      macdTrend: "bullish",
      ma50: 415.6,
      ma200: 392.2,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "moderate",
      volatility: 0.2,
      trendDirection: "uptrend",
      heat: "steady",
      analystSentiment: "cloud and AI platform demand remains constructive",
      earningsSentiment: "positive",
      summary: "MSFT combines durable fundamentals with constructive technical conditions and moderate risk.",
      related: ["AAPL", "NVDA", "AMZN", "QQQ"],
      contentAngles: ["AI infrastructure stocks", "cloud software", "quality large cap"]
    }),
    withStockDefaults({
      symbol: "AMZN",
      type: "stock",
      name: "Amazon.com, Inc.",
      exchange: "NASDAQ",
      sector: "Consumer Cyclical",
      industry: "Internet Retail",
      price: 183.58,
      change: 0.76,
      changePercent: 0.42,
      marketCap: "1.93T",
      peRatio: 38.1,
      revenueGrowth: 0.12,
      profitMargin: 0.1,
      rsi: 55,
      macdTrend: "neutral",
      ma50: 179.4,
      ma200: 166.1,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "moderate",
      volatility: 0.27,
      trendDirection: "uptrend",
      heat: "warm",
      analystSentiment: "cloud margins and retail efficiency are constructive",
      earningsSentiment: "positive",
      summary: "AMZN has constructive trend support with improving profitability, while valuation remains an important risk factor.",
      related: ["MSFT", "META", "AAPL", "SPY"],
      contentAngles: ["cloud demand", "consumer spending", "margin expansion"]
    }),
    withStockDefaults({
      symbol: "META",
      type: "stock",
      name: "Meta Platforms, Inc.",
      exchange: "NASDAQ",
      sector: "Communication Services",
      industry: "Internet Content & Information",
      price: 512.44,
      change: 6.21,
      changePercent: 1.23,
      marketCap: "1.31T",
      peRatio: 27.6,
      revenueGrowth: 0.21,
      profitMargin: 0.34,
      rsi: 62,
      macdTrend: "bullish",
      ma50: 489.8,
      ma200: 432.6,
      volumeTrend: "above average",
      sentiment: "positive",
      risk: "moderate",
      volatility: 0.29,
      trendDirection: "uptrend",
      heat: "hot",
      analystSentiment: "ad cycle and AI engagement signals are constructive",
      earningsSentiment: "positive",
      summary: "META screens well across profitability, trend, and sentiment, with platform and ad-cycle risks still relevant.",
      related: ["AMZN", "MSFT", "QQQ", "SPY"],
      contentAngles: ["digital advertising", "AI engagement", "large-cap growth"]
    }),
    withStockDefaults({
      symbol: "GOOGL",
      type: "stock",
      name: "Alphabet Inc.",
      exchange: "NASDAQ",
      sector: "Communication Services",
      industry: "Internet Content & Information",
      price: 171.28,
      change: 1.04,
      changePercent: 0.61,
      marketCap: "2.10T",
      peRatio: 25.9,
      revenueGrowth: 0.14,
      profitMargin: 0.27,
      rsi: 57,
      macdTrend: "bullish",
      ma50: 166.2,
      ma200: 151.7,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "moderate",
      volatility: 0.24,
      trendDirection: "uptrend",
      heat: "warm",
      analystSentiment: "search advertising and cloud AI demand screen constructively",
      earningsSentiment: "positive",
      summary: "GOOGL screens as a profitable large-cap platform with AI and cloud optionality, balanced by regulatory and competition risks.",
      related: ["META", "MSFT", "AMZN", "QQQ"],
      contentAngles: ["search advertising", "cloud AI", "regulatory risk"]
    }),
    withStockDefaults({
      symbol: "AMD",
      type: "stock",
      name: "Advanced Micro Devices, Inc.",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Semiconductors",
      price: 162.34,
      change: 3.22,
      changePercent: 2.02,
      marketCap: "263B",
      peRatio: 47.4,
      revenueGrowth: 0.18,
      profitMargin: 0.07,
      rsi: 64,
      macdTrend: "bullish",
      ma50: 151.1,
      ma200: 139.8,
      volumeTrend: "above average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.39,
      trendDirection: "uptrend",
      heat: "hot",
      analystSentiment: "AI accelerator competition and data-center demand remain key drivers",
      earningsSentiment: "positive",
      summary: "AMD has constructive AI chip momentum with elevated valuation and margin sensitivity.",
      related: ["NVDA", "AVGO", "SOXX", "QQQ"],
      contentAngles: ["AI accelerator demand", "semiconductor cycles", "data-center growth"]
    }),
    withStockDefaults({
      symbol: "AVGO",
      type: "stock",
      name: "Broadcom Inc.",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Semiconductors",
      price: 1438.2,
      change: 9.8,
      changePercent: 0.69,
      marketCap: "670B",
      peRatio: 36.6,
      revenueGrowth: 0.32,
      profitMargin: 0.24,
      rsi: 60,
      macdTrend: "bullish",
      ma50: 1394.7,
      ma200: 1248.5,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "moderate",
      volatility: 0.3,
      trendDirection: "uptrend",
      heat: "warm",
      analystSentiment: "AI networking and infrastructure software sentiment remains constructive",
      earningsSentiment: "positive",
      summary: "AVGO screens as a semiconductor and infrastructure software candidate with strong margins and moderate risk.",
      related: ["NVDA", "AMD", "SOXX", "XLK"],
      contentAngles: ["AI networking", "infrastructure software", "semiconductor margins"]
    }),
    withStockDefaults({
      symbol: "SMCI",
      type: "stock",
      name: "Super Micro Computer, Inc.",
      exchange: "NASDAQ",
      sector: "Technology",
      industry: "Computer Hardware",
      price: 832.45,
      change: -18.24,
      changePercent: -2.14,
      marketCap: "49B",
      peRatio: 33.8,
      revenueGrowth: 0.52,
      profitMargin: 0.09,
      rsi: 43,
      macdTrend: "bearish",
      ma50: 884.5,
      ma200: 712.4,
      volumeTrend: "above average",
      sentiment: "mixed",
      risk: "high",
      volatility: 0.58,
      trendDirection: "volatile range",
      heat: "volatile",
      analystSentiment: "AI server demand is constructive, while margin and volatility concerns remain elevated",
      earningsSentiment: "mixed",
      summary: "SMCI offers AI server exposure but screens with high volatility and elevated execution risk.",
      related: ["NVDA", "AMD", "SOXX", "QQQ"],
      contentAngles: ["AI server demand", "margin volatility", "customer concentration"]
    }),
    withStockDefaults({
      symbol: "PLTR",
      type: "stock",
      name: "Palantir Technologies Inc.",
      exchange: "NYSE",
      sector: "Technology",
      industry: "Software Infrastructure",
      price: 24.84,
      change: 0.74,
      changePercent: 3.07,
      marketCap: "55B",
      peRatio: 68.2,
      revenueGrowth: 0.21,
      profitMargin: 0.12,
      rsi: 68,
      macdTrend: "bullish",
      ma50: 22.1,
      ma200: 19.7,
      volumeTrend: "above average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.47,
      trendDirection: "uptrend",
      heat: "hot",
      analystSentiment: "AI software demand and enterprise platform adoption are key screening themes",
      earningsSentiment: "positive",
      summary: "PLTR screens as a high-growth AI software candidate with strong momentum and elevated valuation risk.",
      related: ["NVDA", "MSFT", "QQQ", "TSLA"],
      contentAngles: ["AI software demand", "government contracts", "growth-stock volatility"]
    }),
    withEtfDefaults({
      symbol: "SPY",
      name: "SPDR S&P 500 ETF Trust",
      exchange: "NYSE Arca",
      sector: "Broad Market",
      industry: "Large Blend ETF",
      issuer: "State Street Global Advisors",
      category: "U.S. Large Blend",
      expenseRatio: 0.0009,
      price: 526.18,
      change: 1.38,
      changePercent: 0.26,
      peRatio: 24.7,
      rsi: 57,
      macdTrend: "bullish",
      ma50: 518.3,
      ma200: 494.6,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.16,
      trendDirection: "uptrend",
      heat: "steady",
      summary: "SPY represents broad U.S. large-cap market exposure with moderate trend support and diversified risk.",
      holdings: ["MSFT", "AAPL", "NVDA", "AMZN", "META"],
      allocation: { technology: 29, financials: 13, healthcare: 12, consumer: 10, communication: 9, industrials: 8, other: 19 },
      related: ["QQQ", "VOO", "VTI", "AAPL"]
    }),
    withEtfDefaults({
      symbol: "QQQ",
      name: "Invesco QQQ Trust",
      exchange: "NASDAQ",
      sector: "Technology Tilt",
      industry: "Large Growth ETF",
      issuer: "Invesco",
      category: "U.S. Large Growth",
      expenseRatio: 0.002,
      price: 451.72,
      change: 2.04,
      changePercent: 0.45,
      peRatio: 31.8,
      rsi: 61,
      macdTrend: "bullish",
      ma50: 438.6,
      ma200: 414.5,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.22,
      trendDirection: "uptrend",
      heat: "hot",
      summary: "QQQ has stronger growth exposure and momentum than broad market ETFs, with higher concentration and valuation risk.",
      holdings: ["MSFT", "AAPL", "NVDA", "AMZN", "META"],
      allocation: { technology: 49, communication: 15, consumer: 14, healthcare: 6, industrials: 5, other: 11 },
      related: ["SPY", "VTI", "NVDA", "MSFT"]
    }),
    withEtfDefaults({
      symbol: "VTI",
      name: "Vanguard Total Stock Market ETF",
      exchange: "NYSE Arca",
      sector: "Total Market",
      industry: "Total Market ETF",
      issuer: "Vanguard",
      category: "U.S. Total Market",
      expenseRatio: 0.0003,
      price: 258.64,
      change: 0.58,
      changePercent: 0.22,
      peRatio: 23.9,
      rsi: 55,
      macdTrend: "bullish",
      ma50: 253.1,
      ma200: 241.8,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.17,
      trendDirection: "uptrend",
      heat: "steady",
      summary: "VTI screens as broad total-market exposure with lower issuer cost and diversified U.S. equity coverage.",
      holdings: ["MSFT", "AAPL", "NVDA", "AMZN", "META"],
      allocation: { technology: 28, financials: 12, healthcare: 11, consumer: 11, industrials: 9, smallMid: 14, other: 15 },
      related: ["VOO", "SPY", "QQQ", "AAPL"]
    }),
    withEtfDefaults({
      symbol: "VOO",
      name: "Vanguard S&P 500 ETF",
      exchange: "NYSE Arca",
      sector: "Broad Market",
      industry: "Large Blend ETF",
      issuer: "Vanguard",
      category: "U.S. Large Blend",
      expenseRatio: 0.0003,
      price: 483.91,
      change: 1.12,
      changePercent: 0.23,
      peRatio: 24.5,
      rsi: 56,
      macdTrend: "bullish",
      ma50: 476.7,
      ma200: 454.2,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.16,
      trendDirection: "uptrend",
      heat: "steady",
      summary: "VOO offers S&P 500 exposure with a low expense ratio and broad large-cap diversification.",
      holdings: ["MSFT", "AAPL", "NVDA", "AMZN", "META"],
      allocation: { technology: 29, financials: 13, healthcare: 12, consumer: 10, communication: 9, industrials: 8, other: 19 },
      related: ["SPY", "VTI", "QQQ", "MSFT"]
    }),
    withEtfDefaults({
      symbol: "GLD",
      name: "SPDR Gold Shares",
      exchange: "NYSE Arca",
      sector: "Commodities",
      industry: "Gold ETF",
      issuer: "State Street Global Advisors",
      category: "Commodity: Gold",
      expenseRatio: 0.004,
      price: 218.47,
      change: -0.31,
      changePercent: -0.14,
      peRatio: 0,
      revenueGrowth: 0,
      profitMargin: 0,
      rsi: 51,
      macdTrend: "neutral",
      ma50: 216.4,
      ma200: 204.8,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.19,
      trendDirection: "range",
      heat: "cool",
      summary: "GLD is a commodity ETF proxy for gold exposure, with volatility influenced by rates, USD strength, and risk sentiment.",
      holdings: ["Gold bullion exposure"],
      allocation: { gold: 100 },
      related: ["SPY", "QQQ", "VTI", "VOO"]
    }),
    withEtfDefaults({
      symbol: "TLT",
      name: "iShares 20+ Year Treasury Bond ETF",
      exchange: "NASDAQ",
      sector: "Treasury Bonds",
      industry: "Long Treasury Bond ETF",
      issuer: "iShares",
      category: "Long Government Bond",
      expenseRatio: 0.0015,
      price: 92.18,
      change: 0.44,
      changePercent: 0.48,
      peRatio: 0,
      revenueGrowth: 0,
      profitMargin: 0,
      rsi: 54,
      macdTrend: "neutral",
      ma50: 90.8,
      ma200: 94.2,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "elevated",
      volatility: 0.24,
      trendDirection: "range",
      heat: "cool",
      summary: "TLT screens as long-duration Treasury exposure with sensitivity to rates, inflation expectations, and policy outlook.",
      holdings: ["U.S. Treasury 20+ year bonds"],
      allocation: { longTreasury: 100 },
      related: ["GLD", "SPY", "QQQ", "IWM"]
    }),
    withEtfDefaults({
      symbol: "IWM",
      name: "iShares Russell 2000 ETF",
      exchange: "NYSE Arca",
      sector: "Small Cap",
      industry: "Small Blend ETF",
      issuer: "iShares",
      category: "U.S. Small Cap",
      expenseRatio: 0.0019,
      price: 203.76,
      change: 1.86,
      changePercent: 0.92,
      peRatio: 22.4,
      revenueGrowth: 0.06,
      profitMargin: 0.08,
      rsi: 59,
      macdTrend: "bullish",
      ma50: 198.3,
      ma200: 191.4,
      volumeTrend: "above average",
      sentiment: "mixed",
      risk: "elevated",
      volatility: 0.28,
      trendDirection: "rebound",
      heat: "warm",
      summary: "IWM tracks small-cap exposure and can be sensitive to credit conditions, domestic growth, and risk appetite.",
      holdings: ["Russell 2000 diversified small-cap basket"],
      allocation: { financials: 17, industrials: 15, healthcare: 14, technology: 13, consumer: 11, other: 30 },
      related: ["SPY", "QQQ", "VTI", "TLT"]
    }),
    withEtfDefaults({
      symbol: "XLK",
      name: "Technology Select Sector SPDR Fund",
      exchange: "NYSE Arca",
      sector: "Technology",
      industry: "Technology Sector ETF",
      issuer: "State Street Global Advisors",
      category: "Technology Sector",
      expenseRatio: 0.0009,
      price: 214.52,
      change: 1.45,
      changePercent: 0.68,
      peRatio: 33.2,
      rsi: 60,
      macdTrend: "bullish",
      ma50: 207.6,
      ma200: 193.2,
      volumeTrend: "average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.23,
      trendDirection: "uptrend",
      heat: "hot",
      summary: "XLK screens as technology-sector exposure with concentration in large-cap software and hardware leaders.",
      holdings: ["MSFT", "AAPL", "NVDA", "AVGO", "AMD"],
      allocation: { software: 38, hardware: 24, semiconductors: 24, services: 8, other: 6 },
      related: ["QQQ", "SOXX", "NVDA", "MSFT"]
    }),
    withEtfDefaults({
      symbol: "SOXX",
      name: "iShares Semiconductor ETF",
      exchange: "NASDAQ",
      sector: "Semiconductors",
      industry: "Semiconductor ETF",
      issuer: "iShares",
      category: "Semiconductors",
      expenseRatio: 0.0035,
      price: 229.74,
      change: 3.34,
      changePercent: 1.48,
      peRatio: 36.9,
      rsi: 64,
      macdTrend: "bullish",
      ma50: 219.1,
      ma200: 201.6,
      volumeTrend: "above average",
      sentiment: "positive",
      risk: "elevated",
      volatility: 0.31,
      trendDirection: "uptrend",
      heat: "hot",
      summary: "SOXX provides semiconductor ETF exposure and screens with strong AI-chip momentum plus elevated sector volatility.",
      holdings: ["NVDA", "AVGO", "AMD", "semiconductor equipment", "chip designers"],
      allocation: { chipDesigners: 45, equipment: 22, foundry: 14, memory: 8, other: 11 },
      related: ["NVDA", "AMD", "AVGO", "XLK"]
    }),
    withEtfDefaults({
      symbol: "SCHD",
      name: "Schwab U.S. Dividend Equity ETF",
      exchange: "NYSE Arca",
      sector: "Dividend Equity",
      industry: "Dividend ETF",
      issuer: "Schwab",
      category: "U.S. Dividend Equity",
      expenseRatio: 0.0006,
      price: 78.42,
      change: 0.18,
      changePercent: 0.23,
      peRatio: 18.7,
      revenueGrowth: 0.04,
      profitMargin: 0.14,
      rsi: 52,
      macdTrend: "neutral",
      ma50: 77.3,
      ma200: 74.8,
      volumeTrend: "average",
      sentiment: "neutral",
      risk: "moderate",
      volatility: 0.15,
      trendDirection: "steady uptrend",
      heat: "steady",
      summary: "SCHD screens as dividend-oriented equity exposure with lower volatility and value-quality characteristics.",
      holdings: ["dividend quality basket", "financials", "industrials", "healthcare", "consumer staples"],
      allocation: { financials: 18, industrials: 17, healthcare: 15, consumerStaples: 14, technology: 10, other: 26 },
      related: ["VTI", "VOO", "SPY", "TLT"]
    })
  ]
};

export function getMockAssets() {
  return marketUniverse.assets.map((asset) => ({
    ...asset,
    holdings: [...(asset.holdings || [])],
    allocation: asset.allocation ? { ...asset.allocation } : null,
    related: [...(asset.related || [])],
    contentAngles: [...(asset.contentAngles || [])]
  }));
}

function withStockDefaults(asset) {
  return { ...stockDefaults, ...asset };
}

function withEtfDefaults(asset) {
  return { ...etfDefaults, ...asset };
}
